name: release

on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    name: Publish to Visual Studio Code Marketplace
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Make sure the version number in the tag matches the version in package.json
      - name: match-tag-to-package-version
        uses: geritol/match-tag-to-package-version@0.0.2 # https://github.com/geritol/match-tag-to-package-version
        env:
          TAG_PREFIX: refs/tags/v

      # Get the release version for the step "Create GitHub Release"
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      # Get commits summary (ref: https://zenn.dev/seita/articles/d1dba77043be8fd50eeb)
      - name: Get commits summary
        id: get_commit_summary
        run: |
          PREVIOUS_TAG=$(git tag --sort=-creatordate | sed -n 2p)
          echo "PREVIOUS_TAG: $PREVIOUS_TAG"
          COMMIT_SUMMARY="$(git log --oneline --pretty=tformat:"%h %s" $PREVIOUS_TAG..${{ github.ref }})"
          COMMIT_SUMMARY="${COMMIT_SUMMARY//$'\n'/'%0A'}"
          echo ::set-output name=COMMIT_SUMMARY::$COMMIT_SUMMARY

      # Install deps, build, pack and deploy
      - name: Build & Publish
        run: npm install && vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            ${{ steps.get_commit_summary.outputs.COMMIT_SUMMARY }}
          draft: false
          prerelease: false
